name: TickingLocations
version: ${project.version}
main: me.calebtbw.tickinglocations.TickingLocations
api-version: 1.16
authors: [ CalebT ]
description: Getting the location of every block placed in your server
website: http://calebtbw.me
